<a href="https://colab.research.google.com/github/Sophia124990/Tareas_CienciaDatos/blob/main/Tarea_05_Sophia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#autor: Karla Sophia López González
#idautor: 225594-2
#profesor: Lázaro Bustio Martínez

In [ ]:
import numpy as np

# Cargamos los datos desde el archivo CSV, ignorando la primera fila y columna
#que contienen el dia y el número de punto del parque
datos_olas = np.genfromtxt("datos_olas.csv", delimiter=",", skip_header=1, usecols=range(1, 6))

# Imprimimos los datos cargados
print(datos_olas)


[[1.5 2.  1.8 2.1 1.9]
 [1.6 2.1 1.9 2.2 2. ]
 [1.4 1.9 1.7 2.  1.8]
 [1.7 2.3 2.  2.4 2.1]
 [1.5 2.2 1.8 2.3 1.9]]


In [ ]:
#Calculamos la altura promedio de las olas en cada punto del parque acuático durante todos los días
promedios = np.mean(datos_olas, axis=0)

# Imprimimos los resultados
for i, promedio in enumerate(promedios, start=1):
    print(f'Promedio de altura en el Punto {i}: {promedio:.2f}')

Promedio de altura en el Punto 1: 1.54
Promedio de altura en el Punto 2: 2.10
Promedio de altura en el Punto 3: 1.84
Promedio de altura en el Punto 4: 2.20
Promedio de altura en el Punto 5: 1.94


In [ ]:
#Calculamos la altura máxima de las olas en cada punto del parque acuático durante todos los días
maximos = np.max(datos_olas, axis=0)

# Imprimimos los resultados
for i, maximo in enumerate(maximos, start=1):
    print(f'Altura máxima en el Punto {i}: {maximo:.2f}')


Altura máxima en el Punto 1: 1.70
Altura máxima en el Punto 2: 2.30
Altura máxima en el Punto 3: 2.00
Altura máxima en el Punto 4: 2.40
Altura máxima en el Punto 5: 2.10


In [ ]:
#Calculamos la desviación estándar de la altura de las olas en cada punto del parque acuático durante todos los días.
desviaciones_estándar = np.std(datos_olas, axis=0)

# Imprimimos los resultados
for i, desviacion in enumerate(desviaciones_estándar, start=1):
    print(f'Desviación estándar en el Punto {i}: {desviacion:.2f}')

Desviación estándar en el Punto 1: 0.10
Desviación estándar en el Punto 2: 0.14
Desviación estándar en el Punto 3: 0.10
Desviación estándar en el Punto 4: 0.14
Desviación estándar en el Punto 5: 0.10


In [ ]:
#Encontrar el punto del parque acuático con la altura promedio más alta
#mostrar su indice (número de punto) y la altura promedio correspondiente.
indice_punto_maximo = np.argmax(promedios)

# Encuentra los índices de todas las ocurrencias de la altura máxima promedio
altura_maxima = promedios[indice_punto_maximo]

# Imprimimos el resultado
print(f'El punto con la altura promedio más alta es el Punto {indice_punto_maximo + 1} con una altura promedio de {altura_maxima:.2f}')

El punto con la altura promedio más alta es el Punto 4 con una altura promedio de 2.20


In [ ]:
#Encontrar el día con la altura máxima de olas en todo el parque acuático
#mostrar su índice (número de dia) y la altura máxima correspondiente.
altura_maxima_total = np.max(datos_olas)

# Encuentra los índices de todas las ocurrencias de la altura máxima
indice_dia_maximo = np.where(datos_olas == altura_maxima_total)

# Imprimimos el resultado
print(f'El día con la altura máxima de olas en todo el parque acuático es el Día {indice_dia_maximo[0][0] + 1} con una altura máxima de {altura_maxima_total:.2f}')

El día con la altura máxima de olas en todo el parque acuático es el Día 4 con una altura máxima de 2.40


In [ ]:
# Crea un array con los resultados
resultados = np.array([promedios, maximos, desviaciones_estándar])

# Guarda los resultados en un archivo de texto
np.savetxt('resultados_olas.txt', resultados, delimiter=',', fmt='%.2f', header='Promedios, Maximos, Desviaciones')